### PR TITLE
Jeff/clear reconnect

### PR DESCRIPTION
**Pull request by trestletech**
Adds a clear overlay during reconnect to avoid visual gray-out, but does change the cursor to show that it's "thinking" and prohibits further user interaction with the mouse. On disconnect, change the cursor again and gray out.

### CODE REVIEW

**Comment by trestletech** [comment]
CC @wch

**Comment by aronatkins** [comment]
You need to remove `ss-overlay` not `ss-gray-out` on reconnect. The app is not functional on reconnect as is.

**Comment by trestletech** [comment]
Thanks, fixed. But let's actually wait to test this one further until #176 is in. There will be merge conflicts, so I'll bring that one into here once it's merged before we test this one further.

**Comment by aronatkins** [comment]
Ok. Let me know.

**Comment by trestletech** [comment]
Merged in from master. Should be ready now.

**Comment by aronatkins** [comment]
:+1:

**Pull request merged**
