### PR TITLE
Allow whitelisted HTTP headers to pass through to shiny apps

### PR DESCRIPTION
**Pull request by sicarul**
Added whitelist_headers configuration to shiny-server.conf.

This can be useful to adapt a report depending on the browser/referer of the visitor, or to relay additional information from a proxy sitting between the browser and shiny-server.

### CODE REVIEW

**Comment by sicarul** [comment]
image
This is an example of this pull request in action

**Comment by sicarul** [comment]
Ok, i realized this way the headers are only sent the first time the app is accesed, i'll study how can i properly send the headers to the app and fix the PR...

**Comment by jcheng5** [comment]
FYI this functionality is present in shiny server pro. http://docs.rstudio.com/shiny-server/#proxied-headers

If you do want to keep trying on this PR, please try to keep the diffs minimal. The header settings should be applied to the appSpec object. Take a look at other directives that are location-scoped, they should give you a sense of the pattern.

**Comment by sicarul** [comment]
Thanks for the comments @jcheng5. I understood now where should i put the configuation code. Can you help me understand something? From what i see, this function: https://github.com/rstudio/shiny-server/blob/master/lib/router/config-router.js#L123

Is responsible for selecting which app will the user connect to, is that right? Does this mean that if there are no concurrent servers, the same shiny process is "recycled" without reconnecting? I don't understand, if it does that, how is it that when i enter an app the state i see is brand new, i think there's something more i'm not understanding :(

Thanks a lot

**Comment by jcheng5** [comment]
Yes each shiny process can handle multiple connections and each connection can have its own state, because the shiny server function that you define is executed once per session. However the process will only calculate results for one session at a time.

http://shiny.rstudio.com/articles/scoping.html

**Comment by sicarul** [comment]
Ok this has become much more complicated than i thought, mainly because SockJS seems to drop almost all headers, with no way to configure it except merging this PR. https://github.com/sockjs/sockjs-node/pull/202

So i guess you are either using an altered version of SockJS or doing something else to pass those headers, either way, i'll not keep trying for now.

Thanks for the help

**Pull request closed without merging**
