### PR TITLE
Add frequency limiter to dialog changes.

### PR DESCRIPTION
**Pull request by trestletech**
Disposable, but I thought this was a dead-simple way to perhaps address the flicker issue.

@aronatkins If you like it, let's do it. If not, close it and we'll leave it as is.

### CODE REVIEW

**Comment by aronatkins** [comment]
I just tried testing on this branch. On the first reconnect, it seemed to work fine (didn't even see the "Attempting" message). On the second reconnect, the dialog just constantly flipped between "disconnected" and "attempting" (probably on a 500ms timer). And eventually it got stuck in the "Attempting to reconnect" state.

I will continue to test.

**Comment by aronatkins** [comment]
The "Reload" button is also broken with this change.

**Comment by trestletech** [comment]
Weird. As I was going to bed last night I realized I was less sold on this idea. I think the solution is to do it legitimately at some point in the future -- adding a "minimum display time" parameter for messages or something. I'll go ahead and close it if it looks like it's causing bugs for you.

**Comment by aronatkins** [comment]
I think the idea of trying to reduce flickering of the reconnect message is a good one. This wasn't a complete idea. ;)

**Pull request closed without merging**
