### PR TITLE
Patched for Solaris based OS

### PR DESCRIPTION
**Pull request by bhaskarvk**
I patched the cc files for solaris support. This makes shiny server run on solaris and derived OSes like SmartOS etc.

### CODE REVIEW

**Comment by jcheng5** [comment]
Thanks! Where did the getgrouplist code come from, is that your original code?

**Comment by bhaskarvk** [comment]
@jcheng5 I copied it from https://github.com/wired/kde-overlay/blob/master/kde-base/kdelibs/files/kdelibs-4.3.2-solaris-getgrouplist.patch. Better make sure proper licensing stuff.

**Comment by bhaskarvk** [comment]
Hi @jcheng5 Any updates on this PR ?

**Comment by jcheng5** [comment]
Sorry, it's been a crazy week. This copy is licensed under the 4-clause BSD license which is not easy to mix with other open source software these days due to the advertising clause. If you could find a 3-clause BSD licensed copy, we could use that.

**Comment by bhaskarvk** [comment]
No worries, I might just write my own implementation.

**Pull request closed without merging**
