### PR TITLE
Update to latest node http-proxy

### PR DESCRIPTION
**Pull request by trestletech**
This PR might be worth more discussion/review.

Note that this is a hybrid of our fork and the new master. Given that the remote is a ground-up rewrite, we're presumably better off just going to their master branch. But more investigating can be done.

This fixes the `" req.resume error: Cannot call method 'resume' of null"` errors we get when using packages like e.g. DT. 

I do have a repro case for this error but can't post it publicly.

### CODE REVIEW

**Comment by aronatkins** [comment]
Renamed PR to better reflect change.

**Comment by trestletech** [comment]
After reviewing our changes, I'm tempted to say we actually just go to their master branch. Thoughts?

**Comment by trestletech** [comment]
Update to their master branch. Wait to merge until we have a build we like with the error logging.

**Comment by aronatkins** [comment]
:+1:

**Comment by jcheng5** [comment]
Doing this as part of the move to Node v6

**Pull request closed without merging**
