### PR TITLE
Support gzip/deflate compression for HTTP responses

### PR DESCRIPTION
**Pull request by jcheng5**
Testing notes: Use Chrome network inspector to see if HTTP responses include `Content-Encoding: gzip` headers.

### CODE REVIEW

**Comment by jcheng5** [comment]
- [ ] Make sure that downstream proxy calls don't include the gzip header

**Comment by jcheng5** [comment]
@alandipert This should be ready to merge. I had said we needed to test that the wrong headers didn't make it to httpuv but that doesn't make any sense; this feature doesn't change the behavior of requests, only responses.

**Comment by shalutiwari** [comment]
Should this be seen in any of the Sample apps or the welcome/admin page?

**Comment by jcheng5** [comment]
I believe it will not work on the admin port, but should work literally
everywhere else.

**Comment by alandipert** [comment]
@shalutiwari just in case you're interested, a command-line way to QA is this: run `curl -H "Accept-Encoding: gzip" -L -I http://localhost:3838/` and look for `content-encoding: gzip` in the list of headers printed out.

**Comment by shalutiwari** [comment]
@alandipert I don't see it there.

[vagrant@sso-centos7-latest ~]$ shiny-server --version
Shiny Server (Commercial) v1.5.7.923
Node.js v6.10.3
[vagrant@sso-centos7-latest ~]$ curl -H "Accept-Encoding: gzip" -L -I http://localhost:3838/
HTTP/1.1 403 Forbidden
X-Powered-By: Express
Set-Cookie: _csrf=IMN7whf-yNFuU84FDfD4ESFu; Path=/
Set-Cookie: SSP-XSRF=K1VUp4G3-CNPl2-CnrbLxyF23BhMsZlHPNco; Path=/
Set-Cookie: session_state=6bmvlwWhVWbgDHa-8cu_bw.JS3Ju2B9ALr9XhNVDfD1TmT5IVj1TPNQfly417wK9n29JDhTm3vt1WGPMrqHxAWqIWqElyg7WxyeMJTqD2_MGA.1520440343986.7200000.Wt0f-JT64Qpy9cMTSSjPGg_FvsJajrdxMtMok7V7Y3k; path=/; expires=Wed, 07 Mar 2018 18:32:24 GMT; httponly
X-Frame-Options: DENY
Content-Type: text/html; charset=utf-8
Vary: Accept-Encoding
Date: Wed, 07 Mar 2018 16:32:23 GMT
Connection: keep-alive

**Comment by shalutiwari** [comment]
On the Welcome page click on sample-apps/hello. Then open chrome inspector and in Network section. Click on any of the names row and view the headers. There in response-headers you can verify that there is content-encoding:gzip present .

Verified on Shiny Server (Commercial) v1.5.7.923

**Pull request merged**
